### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by alrik** [realmq/realmq-platform#88]
This is a meta issue for keeping track on the dashboard.<br>

**Goal**<br>
The purpose of the dashboard web app is to improve account & realm management.

**Todos**
* [ ] Write dashboard specification
* [x] Implement the dashboard
* [ ] Write dashboard documentation

:point_right: _Thanks for votes and comments to help us prioritize_

**Comment by alrik** [comment]
https://marmelab.com/react-admin/
