### ISSUE TITLE
Channel Pipes

### ISSUE THREAD

**Issue by alrik** [realmq/realmq-platform#89]
This is a meta ticket for discussing & keeping track on channel pipes.

**Abstract**<br>
Channel Pipes are an advanced feature to control and manipulate data flows. Their base functionality is to route traffic from a list of source channels to a list of target channels.
A webhook on a pipe allows for filtering and routing the traffic on message level. Pipes are very handy for building any kind of automation on top of messaging (e.g. chatbots).

**Todos**
* [ ] Specification of channel pipes
* [ ] Implementation of channel pipes
* [ ] Documentation of channel pipes

:point_right: _Thanks for votes and comments to help us prioritize_
